name: le_chef
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^1.1.6
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2
  flutter_credit_card: ^4.0.1
  cupertino_icons: ^1.0.2
  majesticons_flutter:  ^0.0.1
  iconsax: ^0.0.8
  get: ^4.6.6
  solar_icons: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
