name: le_chef
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^1.1.6
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2
  flutter_credit_card: ^4.0.1
  cupertino_icons: ^1.0.2
  majesticons_flutter:  ^0.0.1
  iconsax: ^0.0.8
  get: ^4.6.6
  flutter_chat_ui: ^1.6.14
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  animations: ^2.0.5
  mime: ^1.0.5
  open_filex: ^4.4.0
  solar_icons: ^0.0.5
  flutter_sound: ^9.0.9+1
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  uuid: ^3.0.5
  flutter_chat_types: ^3.6.2
  http: ^1.2.2
  just_waveform: ^0.0.5
  audioplayers: ^6.0.0
  audio_service: ^0.18.15
  flutter_screenutil: ^5.9.3
  just_audio: ^0.9.39
  shared_preferences: ^2.3.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3


  intl: any
  flutter_webrtc: ^0.11.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/