// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1QWonIZ4Xd6gqzkqO7A9ZTBUe0mrrkc',
    appId: '1:946223223060:web:22311bc7d09e3ee38ab201',
    messagingSenderId: '946223223060',
    projectId: 'le-chef-1',
    authDomain: 'le-chef-1.firebaseapp.com',
    storageBucket: 'le-chef-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5UkE8-GLr8U2GdYrfy14KdWU0w5GQ9s',
    appId: '1:946223223060:android:74b9fca8e519a9a48ab201',
    messagingSenderId: '946223223060',
    projectId: 'le-chef-1',
    storageBucket: 'le-chef-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7VVWnqKM-O3VDYWapje7zmlZz4fg25g',
    appId: '1:946223223060:ios:8c5d8872ab686fa18ab201',
    messagingSenderId: '946223223060',
    projectId: 'le-chef-1',
    storageBucket: 'le-chef-1.firebasestorage.app',
    iosBundleId: 'com.example.leChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7VVWnqKM-O3VDYWapje7zmlZz4fg25g',
    appId: '1:946223223060:ios:8c5d8872ab686fa18ab201',
    messagingSenderId: '946223223060',
    projectId: 'le-chef-1',
    storageBucket: 'le-chef-1.firebasestorage.app',
    iosBundleId: 'com.example.leChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd1QWonIZ4Xd6gqzkqO7A9ZTBUe0mrrkc',
    appId: '1:946223223060:web:f7b6819ba2dfb8ad8ab201',
    messagingSenderId: '946223223060',
    projectId: 'le-chef-1',
    authDomain: 'le-chef-1.firebaseapp.com',
    storageBucket: 'le-chef-1.firebasestorage.app',
  );

}